# Generated by Django 2.1.1 on 2018-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=20)),
                ('image_description', models.TextField(max_length=200)),
            ],
        ),
    ]
