# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beautiful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GirlName', models.CharField(max_length=20)),
                ('ImageUrl', models.CharField(max_length=200)),
            ],
        ),
    ]
